
  const ADD_DETAILS="ADD_DETAILS";
  const UPDATE_DETAILS="UPDATE_DETAILS";
  const SELECT_DETAILS="SELECT_DETAILS";
  const DELETE_USER="DELETE_USER";

  export{ADD_DETAILS,UPDATE_DETAILS,SELECT_DETAILS,DELETE_USER}